# This SPARQL replaces blank nodes in subject position at the top level.
PREFIX schema: <http://schema.org/>
DELETE {
  ?blank_node ?p ?o 
}

INSERT {
  ?uuid_uri ?p ?o 
}

WHERE {
  {
    SELECT DISTINCT ?blank_node  
    WHERE {
      values ?type { schema:LocalBusiness schema:Place }
      ?blank_node a ?type . 
      FILTER (isBLANK(?blank_node))
      FILTER NOT EXISTS { ?other_s ?other_p ?blank_node }
    }
  }
  bind(URI("place_url") as ?uuid_uri)
  ?blank_node ?p ?o 
}