PREFIX schema: <http://schema.org/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

delete {
    graph <http://kg.artsdata.ca/culture-creates/artsdata-planet-ville-de-laval/calendrier-activites> {
        ?s  schema:startDate ?startDate;
            schema:endDate ?endDate .
    }
}
insert {
    graph <http://kg.artsdata.ca/culture-creates/artsdata-planet-ville-de-laval/calendrier-activites> {
        ?s  schema:startDate ?startDateFix ;
            schema:endDate ?endDateFix .
    }
}

where {
    graph <http://kg.artsdata.ca/culture-creates/artsdata-planet-ville-de-laval/calendrier-activites> {
        ?s a schema:Event ;
           schema:startDate ?startDate ;
           schema:name ?name  ;
           schema:endDate ?endDate ;
           schema:location ?loc .
        bind(strdt(concat(str(?startDate),"Z"),xsd:dateTime) as ?startDateFix)
        bind(strdt(concat(str(?endDate),"Z"),xsd:dateTime) as ?endDateFix)
    }
    filter(!strends(str(?startDate),"Z"))
    filter(!strends(str(?endDate),"Z"))
}