name: Send place mapping to Artsdata databus
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set current date as output
        id: version  # this is used on variable path
        run: echo "dumpdate=$(date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_OUTPUT
      - name: Register dump in Artsdata Databus  # TODO add "reportCallbackUrl" to Github logs
        run: |
          curl \
          -H 'Content-Type: application/json' \
          -X POST http://api.artsdata.ca/databus/  \
          --data '{ "publisher": "https://saumier.github.io/gregory-saumier-finch.ttl%23this",
                    "group": "artsdata-planet-ville-de-laval",
                    "artifact": "place-mapping-to-artsdata",
                    "version": "place-mapping-to-artsdata-${{ steps.version.outputs.dumpdate }}",
                    "downloadUrl": "https://raw.githubusercontent.com/culturecreates/artsdata-planet-ville-de-laval/main/mapping/place-mapping-to-artsdata.ttl",
                    "downloadFile": "place-mapping-to-artsdata-${{ steps.version.outputs.dumpdate }}.ttl",
                    "comment": "Mapping of Laval Place IDs to Artsdata Place URIs",
                    "reportCallbackUrl": "https://footlight-condenser.herokuapp.com/messages/webhook.json?artifact=place-mapping-to-artsdata",
                    "shacl": "artsdata"
                  }'   
